### ISSUE TITLE
Docker cannot find file dependencies on Ubuntu 18.04

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/decimal-reference#2]
When running the command:
```
sudo docker run -it --rm decimal-reference
```
Gives the error 
```
/usr/local/bin/dectest: error while loading shared libraries: libdfp.so.1: cannot open shared object file: No such file or directory
```

**Comment by juliaogris** [comment]
@camh-anz is the resident linux guru, if he can be sidetracked from being sidetracked.

**Comment by camscale** [comment]
The host OS (ubuntu 18.04) should not matter as docker isolates that.

That aside, I can't see how this happens. The dockerfile copies `libdfp.so.1` to `/usr/local/lib` and also sets `LD_LIBRARY_PATH`. Unless maybe your `src/` directory was not clean on the host (it copies it all, so maybe there's some cross-os issue?) - if `src/` has anything other than `main.c` in it, clean it out (`git clean -dfx` is the easiest way - beware, you'll lose all non-repository files).
